services:
  - type: web
    name: taxing-solutions-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        value: your-super-secret-jwt-key-here-make-it-very-long-and-random-1234567890
      - key: DATABASE_PATH
        value: /opt/render/project/src/users.db
